import { createFileRoute } from "@tanstack/react-router";

// Twilio status callback. Twilio POSTs application/x-www-form-urlencoded.
// We authenticate the caller via a shared secret in the query string
// (Twilio has no OAuth; the token is generated by us and only Twilio + our
// own server know it because we passed it as the StatusCallback URL).
export const Route = createFileRoute("/api/public/twilio/call-status")({
  server: {
    handlers: {
      POST: async ({ request }) => {
        const url = new URL(request.url);
        const token = url.searchParams.get("token") ?? "";
        const expected = process.env.TWILIO_WEBHOOK_SECRET ?? "";
        if (!expected || token !== expected) {
          return new Response("forbidden", { status: 403 });
        }

        const form = await request.formData();
        const sid = String(form.get("CallSid") ?? "");
        const status = String(form.get("CallStatus") ?? "");
        if (!sid || !status) return new Response("bad request", { status: 400 });

        const durationRaw = form.get("CallDuration");
        const duration = durationRaw ? Number(durationRaw) : null;
        const recordingUrl = form.get("RecordingUrl");
        const errorCode = form.get("ErrorCode");
        const errorMessage = form.get("ErrorMessage");

        const patch: {
          status: string;
          duration_seconds?: number;
          recording_url?: string;
          error_code?: string;
          error_message?: string;
          started_at?: string;
          ended_at?: string;
        } = { status };
        if (duration && !Number.isNaN(duration)) patch.duration_seconds = duration;
        if (recordingUrl) patch.recording_url = String(recordingUrl);
        if (errorCode) patch.error_code = String(errorCode);
        if (errorMessage) patch.error_message = String(errorMessage);
        if (status === "in-progress" || status === "answered") {
          patch.started_at = new Date().toISOString();
        }
        if (status === "completed" || status === "failed" || status === "busy" || status === "no-answer" || status === "canceled") {
          patch.ended_at = new Date().toISOString();
        }

        const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
        const { error } = await supabaseAdmin
          .from("calls")
          .update(patch)
          .eq("twilio_call_sid", sid);
        if (error) {
          console.error("call-status update failed", error);
          return new Response("error", { status: 500 });
        }
        return new Response("ok");
      },
    },
  },
});
